plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - "@semantic-release/github"

branches:
  - main
  - name: dev/*
    prerelease: "dev"
  - name: feature/*
    prerelease: "feature"
  - name: hotfix/*
    prerelease: "hotfix"
  - name: intern/*
    prerelease: "intern"