import {Table, TablePOS} from "./types.ts";

const mockTables: TablePOS[] = [
    {
        id: 1,
        number: 1,
        status: 'open',
        isOccupied: true,
        openedAt: '2025-06-04T14:00:00Z',
        waiterId: 101,
        waiterName: 'Carlos',
        totalOrderValue: 145.75,
        pendingItems: 1,
        seatsOccupied: 3,
        table: {
            id: 1,
            name: 'Mesa 1',
            number: 1,
            x: 100,
            y: 100,
            seats: 4,
            bgColor1: '#2196F3',
            bgColor2: '#1565C0',
            fontColor: '#FFFFFF',
            shape: 'rectangle',
            width: 150,
            height: 150,
            rotation: 0
        }
    },
    {
        id: 2,
        number: 2,
        status: 'reserved',
        isReserved: true,
        reservedAt: '2025-06-04T20:00:00Z',
        reservedFor: 'Ana Paula',
        reservationNotes: 'Aniversário - 6 pessoas',
        seatsOccupied: 0,
        table: {
            id: 2,
            name: 'Mesa 2',
            number: 2,
            x: 300,
            y: 100,
            seats: 6,
            bgColor1: '#FF9800',
            bgColor2: '#F57C00',
            fontColor: '#000000',
            shape: 'rectangle',
            width: 150,
            height: 150,
            rotation: 0
        }
    },
    {
        id: 3,
        number: 3,
        status: 'closed',
        lastOccupiedAt: '2025-06-04T17:45:00Z',
        isOccupied: false,
        seatsOccupied: 0,
        table: {
            id: 3,
            name: 'Mesa 3',
            number: 3,
            x: 500,
            y: 100,
            seats: 2,
            bgColor1: '#9E9E9E',
            bgColor2: '#757575',
            fontColor: '#FFFFFF',
            shape: 'circle',
            width: 150,
            height: 150,
            rotation: 0
        }
    },
    {
        id: 4,
        number: 4,
        status: 'open',
        isOccupied: true,
        openedAt: '2025-06-04T13:15:00Z',
        waiterId: 102,
        waiterName: 'Marina',
        seatsOccupied: 4,
        pendingItems: 3,
        totalOrderValue: 212.00,
        table: {
            id: 4,
            name: 'Mesa 4',
            number: 4,
            x: 100,
            y: 250,
            seats: 4,
            bgColor1: '#4CAF50',
            bgColor2: '#2E7D32',
            fontColor: '#FFFFFF',
            shape: 'square',
            width: 150,
            height: 150,
            rotation: 0
        }
    },
    {
        id: 5,
        number: 5,
        status: 'blocked',
        isOccupied: false,
        seatsOccupied: 0,
        table: {
            id: 5,
            name: 'Mesa 5',
            number: 5,
            x: 300,
            y: 250,
            seats: 4,
            bgColor1: '#E91E63',
            bgColor2: '#AD1457',
            fontColor: '#FFFFFF',
            shape: 'rectangle',
            width: 150,
            height: 150,
            rotation: 0
        }
    },
    {
        id: 6,
        number: 6,
        status: 'cleaning',
        lastOccupiedAt: '2025-06-04T18:10:00Z',
        seatsOccupied: 0,
        table: {
            id: 6,
            name: 'Mesa 6',
            number: 6,
            x: 500,
            y: 250,
            seats: 6,
            bgColor1: '#00BCD4',
            bgColor2: '#00838F',
            fontColor: '#000000',
            shape: 'rectangle',
            width: 150,
            height: 150,
            rotation: 0
        }
    },
    {
        id: 7,
        number: 7,
        status: 'open',
        isOccupied: false,
        waiterId: 103,
        waiterName: 'Fernanda',
        seatsOccupied: 0,
        table: {
            id: 7,
            name: 'Mesa 7',
            number: 7,
            x: 100,
            y: 400,
            seats: 2,
            bgColor1: '#FFC107',
            bgColor2: '#FFA000',
            fontColor: '#000000',
            shape: 'circle',
            width: 150,
            height: 150,
            rotation: 0
        }
    },
    {
        id: 8,
        number: 8,
        status: 'open',
        isGrouped: true,
        groupId: 1,
        isOccupied: true,
        waiterId: 104,
        waiterName: 'Lucas',
        seatsOccupied: 3,
        openedAt: '2025-06-04T14:50:00Z',
        totalOrderValue: 320.90,
        table: {
            id: 8,
            name: 'Mesa 8',
            number: 8,
            x: 300,
            y: 400,
            seats: 4,
            bgColor1: '#3F51B5',
            bgColor2: '#1A237E',
            fontColor: '#FFFFFF',
            shape: 'rectangle',
            width: 150,
            height: 150,
            rotation: 0
        }
    },
    {
        id: 9,
        number: 9,
        status: 'open',
        isGrouped: true,
        groupId: 1,
        isOccupied: true,
        waiterId: 104,
        waiterName: 'Lucas',
        seatsOccupied: 2,
        openedAt: '2025-06-04T15:10:00Z',
        totalOrderValue: 320.90,
        table: {
            id: 9,
            name: 'Mesa 9',
            number: 9,
            x: 440,
            y: 400,
            seats: 4,
            bgColor1: '#3F51B5',
            bgColor2: '#1A237E',
            fontColor: '#FFFFFF',
            shape: 'rectangle',
            width: 150,
            height: 150,
            rotation: 0
        }
    },
    {
        id: 10,
        number: 10,
        status: 'closed',
        isOccupied: false,
        seatsOccupied: 0,
        lastOccupiedAt: '2025-06-04T18:40:00Z',
        table: {
            id: 10,
            name: 'Mesa 10',
            number: 10,
            x: 600,
            y: 400,
            seats: 6,
            bgColor1: '#9C27B0',
            bgColor2: '#6A1B9A',
            fontColor: '#FFFFFF',
            shape: 'square',
            width: 150,
            height: 150,
            rotation: 0
        }
    }
]


const mocTables2 : Table[] =
    [
        {
            id: 'kjk',
            x: 0,
            y: 100,
            number: 1,
            fontColor: '#FFFFFF',
            seats: 4,
            bgColor1: '#2196F3',
            bgColor2: '#1565C0',
            shape: 'rectangle',
            width: 200,
            height: 200,
            status: 'closed',
            openedAt: '',
            waiterName: '',
            pendingItems: 1,
            seatsOccupied: 3,
            name: 'Table 1',
            isOccupied: false,
            isCleaning: false,

        },
        {
            id: 'kjsk',
            x: 300,
            y: 100,
            number: 1,
            fontColor: '#FFFFFF',
            seats: 4,
            bgColor1: '#2196F3',
            bgColor2: '#1565C0',
            shape: 'rectangle',
            width: 200,
            height: 200,
            status: 'closed',
            openedAt: '',
            waiterName: '',
            pendingItems: 1,
            seatsOccupied: 3,
            name: 'Table 2',
            isOccupied: false,
            isCleaning: false,

        },
        {
            id: 'kssjsk',
            x: 600,
            y: 100,
            number: 1,
            fontColor: '#FFFFFF',
            seats: 4,
            bgColor1: '#2196F3',
            bgColor2: '#1565C0',
            shape: 'circle',
            width: 200,
            height: 200,
            status: 'closed',
            openedAt: '',
            waiterName: '',
            pendingItems: 1,
            seatsOccupied: 3,
            name: 'Table 2',
            isOccupied: false,
            isCleaning: false,

        }
    ];

const mocTables3 : Table[] =
    [
        {
            id: 'kjk',
            x: 0,
            y: 0,
            number: 1,
            fontColor: '#FFFFFF',
            seats: 4,
            bgColor1: '#2196F3',
            bgColor2: '#1565C0',
            shape: 'rectangle',
            width: 2,
            height: 2,
            status: 'closed',
            openedAt: '',
            waiterName: '',
            pendingItems: 1,
            seatsOccupied: 3,
            name: 'Table 1',
            isOccupied: false,
            isCleaning: false,

        },
        {
            id: 'kjsk',
            x: 1,
            y: 0,
            number: 1,
            fontColor: '#FFFFFF',
            seats: 4,
            bgColor1: '#2196F3',
            bgColor2: '#1565C0',
            shape: 'rectangle',
            width: 2,
            height: 2,
            status: 'closed',
            openedAt: '',
            waiterName: '',
            pendingItems: 1,
            seatsOccupied: 3,
            name: 'Table 2',
            isOccupied: false,
            isCleaning: false,

        },
        {
            id: 'kjsfssk',
            x: 2,
            y: 0,
            number: 1,
            fontColor: '#FFFFFF',
            seats: 4,
            bgColor1: '#2196F3',
            bgColor2: '#1565C0',
            shape: 'rectangle',
            width: 2,
            height: 2,
            status: 'closed',
            openedAt: '',
            waiterName: '',
            pendingItems: 1,
            seatsOccupied: 3,
            name: 'Table 3',
            isOccupied: false,
            isCleaning: false,

        },
        {
            id: 'kk',
            x: 3,
            y: 0,
            number: 1,
            fontColor: '#FFFFFF',
            seats: 4,
            bgColor1: '#2196F3',
            bgColor2: '#1565C0',
            shape: 'rectangle',
            width: 2,
            height: 2,
            status: 'closed',
            openedAt: '',
            waiterName: '',
            pendingItems: 1,
            seatsOccupied: 3,
            name: 'Table 4',
            isOccupied: false,
            isCleaning: false,

        },
        {
            id: 'kjsfssk254',
            x: 4,
            y: 0,
            number: 1,
            fontColor: '#FFFFFF',
            seats: 4,
            bgColor1: '#2196F3',
            bgColor2: '#1565C0',
            shape: 'rectangle',
            width: 2,
            height: 2,
            status: 'closed',
            openedAt: '',
            waiterName: '',
            pendingItems: 1,
            seatsOccupied: 3,
            name: 'Table 5',
            isOccupied: false,
            isCleaning: false,

        }
    ];

export {mockTables, mocTables2, mocTables3};
