name: Semantic Release

on:
  push:
    branches:
      - master
      - dev/*
      - feature/*
      - hotfix/*
      - release/*
      - intern/*

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Semantic Release
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Instala o pnpm no Windows runner
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install

      - name: Prepare prerelease semantic
        if: github.ref != 'refs/heads/main'
        run: mv .releaserc.prerelease.yaml .releaserc.yaml

      - name: Build and publish Electron app
        run: pnpm exec electron-builder --publish always
        env:
          GH_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 17
          extra_plugins: |
            @semantic-release/changelog@5
            @semantic-release/exec@5
            @semantic-release/git@9
        env:
          GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}